name: Say Hello
on:
  push:
    branches:
      - main # the name of your main branch
  workflow_dispatch:
    inputs:
      USER_NAME:
        required: true
        type: string
jobs:
  sayhello:
    name: SayHello
    environment: smbc-dev
    runs-on: [self-hosted, java-build]
    steps:
      - name: Say Hello
        run: echo "Hello!!!"
